### ISSUE TITLE
Emitting works but receiving doesn't

### ISSUE THREAD

**Issue by rlaferla** [MegaBits/SIOSocket#10]
I'm using socket io 1.1.0.  My app can connect, emit but not receive data from the server.  Is the issue the socket io version?

**Comment by alexeyhippie** [comment]
Still had similar this issue, also with double quotes too, on v0.2.0;
Fix it with escaping as @usandfriends suggest 
```
var escData = data.stringByReplacingOccurrencesOfString("\'", withString: "\\\'", options: NSStringCompareOptions.CaseInsensitiveSearch, range: nil)
        escData = escData.stringByReplacingOccurrencesOfString("\"", withString: "\\\"", options: NSStringCompareOptions.CaseInsensitiveSearch, range: nil)
```
then this escData goes to emit method args like

```
self.socket.emit(kSendMessageActionName, args: [escData])
```
